services:
  live:
    build:
      context: .
      target: live
    restart: always
    ports:
      - 4000:4000
    environment:
      - LIVE_BACKEND_ADDRESS=0.0.0.0:4000
      - ORIGIN=https://f1onboard.azurewebsites.net
      - RUST_LOG=live=trace

  api:
    build:
      context: .
      target: api
    restart: always
    ports:
      - 4001:4001
    environment:
      - API_BACKEND_ADDRESS=0.0.0.0:4001
      - RUST_LOG=api=debug
 
  frontend:
    build:

      context: ./dash/
      args:
        - NEXT_PUBLIC_LIVE_SOCKET_URL=https://live-6bcf.onrender.com
        - NEXT_PUBLIC_API_URL=https://live-6bcf.onrender.com
        - TAG=latest


    restart: always
    ports:
      - 3000:3000
    depends_on:
      - api
      - live
    environment:
      - NEXT_PUBLIC_LIVE_SOCKET_URL=https://live-6bcf.onrender.com
      - NEXT_PUBLIC_API_URL=https://live-6bcf.onrender.com
